### ISSUE TITLE
Question about throughput

### ISSUE THREAD

**Issue by victorshoup** [AndersTrier/reed-solomon-simd#14]
Just a quick question: in the benchmark program, why is throughput measured in terms of original_shards+recovery_shards? I mean, the "real" data is original_shards, and it seems to me that just using original_shards is more natural/meaningful. But I understand that this is just a matter of definition, I suppose.

Btw, I've been running various benchmarks...this does seem like it achieves amazing performance! Bravo!!

**Comment by AndersTrier** [comment]
This project is a fork of [reed-solomon-16](https://crates.io/crates/reed-solomon-16). I didn't touch the benchmark code much.

Anyways, I would like the benchmark numbers to be comparable to the table on [https://github.com/klauspost/reedsolomon/](https://github.com/klauspost/reedsolomon/). Klaus states that `Speed is total shard size for each operation`.
If my benchmark is working differently from Klaus benchmark, feel free to submit a PR.

> Btw, I've been running various benchmarks...this does seem like it achieves amazing performance! Bravo!!

Thanks!
