### ISSUE TITLE
How to process data using the streaming method

### ISSUE THREAD

**Issue by nanakura** [AndersTrier/reed-solomon-simd#47]
How to use this crate to process large files
like this https://github.com/klauspost/reedsolomon/blob/master/examples/stream-encoder.go

**Comment by AndersTrier** [comment]
Not implemented yet.
As a workaround, how about splitting the large file up into smaller chunks that fit in RAM and process each chunk individually? Could that work for you?

**Comment by nanakura** [comment]
I will try
